"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Status = "cadastrado" | "disponivel" | "reservado" | "vendido";
type Vehicle = { id:number; brand:string; model:string; year:string; mileage:number; plate:string; status:Status; damages:string[]; notes:string; photoUrl:string|null; color:string };
type Draft = Omit<Vehicle,"id"> & { damageText:string };

const labels: Record<Status,string> = { cadastrado:"Cadastrado", disponivel:"Disponível", reservado:"Reservado", vendido:"Vendido" };
const emptyDraft: Draft = { brand:"", model:"", year:"", mileage:0, plate:"", status:"cadastrado", damages:[], damageText:"", notes:"", photoUrl:null, color:"#69706f" };

function CarArt({ vehicle }:{ vehicle:Vehicle }) {
  if (vehicle.photoUrl) return <div className="car-art photo"><img src={vehicle.photoUrl} alt={`${vehicle.brand} ${vehicle.model}`} /></div>;
  return <div className="car-art" style={{"--car-color":vehicle.color} as React.CSSProperties}><span></span></div>;
}

export default function Home() {
  const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [loading,setLoading]=useState(true);
  const [role,setRole]=useState<"admin"|"vendedor">("vendedor"); const [query,setQuery]=useState(""); const [filter,setFilter]=useState<"todos"|Status>("todos");
  const [selected,setSelected]=useState<Vehicle|null>(null); const [showFilters,setShowFilters]=useState(false); const [toast,setToast]=useState("");
  const [formOpen,setFormOpen]=useState(false); const [editingId,setEditingId]=useState<number|null>(null); const [draft,setDraft]=useState<Draft>(emptyDraft); const [saving,setSaving]=useState(false); const [error,setError]=useState("");

  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  const load=async()=>{setLoading(true);try{const res=await fetch("/api/vehicles",{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error);setVehicles(data.vehicles)}catch{notify("Não foi possível atualizar o estoque") }finally{setLoading(false)}};
  useEffect(()=>{load()},[]);

  const visible=useMemo(()=>vehicles.filter(v=>(role==="admin"||v.status==="disponivel")&&(filter==="todos"||v.status===filter)&&`${v.brand} ${v.model} ${v.plate}`.toLowerCase().includes(query.toLowerCase())),[vehicles,role,filter,query]);
  const count=(status:Status)=>vehicles.filter(v=>v.status===status).length;
  const openCreate=()=>{setEditingId(null);setDraft(emptyDraft);setError("");setFormOpen(true)};
  const openEdit=(v:Vehicle)=>{setEditingId(v.id);setDraft({...v,damageText:v.damages.join("\n")});setSelected(null);setError("");setFormOpen(true)};
  const upload=async(file:File)=>{const form=new FormData();form.append("file",file);const res=await fetch("/api/uploads",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error);setDraft(d=>({...d,photoUrl:data.url}))};
  const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const payload={...draft,damages:draft.damageText.split("\n").map(x=>x.trim()).filter(Boolean)};const res=await fetch(editingId?`/api/vehicles/${editingId}`:"/api/vehicles",{method:editingId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error);setFormOpen(false);await load();notify(editingId?"Veículo atualizado":"Veículo cadastrado")}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar")}finally{setSaving(false)}};
  const changeStatus=async(v:Vehicle,status:Status)=>{const res=await fetch(`/api/vehicles/${v.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});if(res.ok){setSelected(null);await load();notify(`Status alterado para ${labels[status]}`)}else notify("Não foi possível alterar o status")};

  return <main className="app-shell">
    <header className="topbar"><div className="brand">Auto<span>Estoque</span></div><div className="role-switch" aria-label="Alternar perfil"><button className={role==="vendedor"?"active":""} onClick={()=>{setRole("vendedor");setFilter("todos")}}>Vendedor</button><button className={role==="admin"?"active":""} onClick={()=>setRole("admin")}>Administrativo</button></div>{role==="admin"&&<button className="primary desktop-action" onClick={openCreate}>＋ Cadastrar veículo</button>}</header>
    <section className="hero"><div><p className="eyebrow">{role==="admin"?"GESTÃO DA FROTA":"CATÁLOGO DA CONCESSIONÁRIA"}</p><h1>{role==="admin"?"Visão geral do estoque":"Encontre o carro certo"}</h1><p>{role==="admin"?"Cadastre, acompanhe e atualize o fluxo de venda.":"Estoque atualizado para consultar e negociar sem ligações."}</p></div><button className="sync" onClick={load}><i></i> Atualizar estoque</button></section>
    {role==="admin"&&<section className="kpis" aria-label="Resumo do estoque"><button onClick={()=>setFilter("disponivel")}><span>Disponíveis</span><strong>{count("disponivel")}</strong><small>Prontos para venda</small></button><button onClick={()=>setFilter("reservado")}><span>Reservados</span><strong>{count("reservado")}</strong><small>Aguardando confirmação</small></button><button onClick={()=>setFilter("vendido")}><span>Vendidos</span><strong>{count("vendido")}</strong><small>Histórico da frota</small></button></section>}
    <section className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar marca, modelo ou placa"/></label>{role==="admin"&&<button className="filter-trigger" onClick={()=>setShowFilters(!showFilters)}>☷ Filtros <b>{filter!=="todos"?"1":""}</b></button>}{showFilters&&role==="admin"&&<div className="filter-sheet"><div><strong>Filtrar por status</strong><button onClick={()=>setShowFilters(false)}>×</button></div>{(["todos","cadastrado","disponivel","reservado","vendido"] as const).map(item=><button key={item} className={filter===item?"selected":""} onClick={()=>{setFilter(item);setShowFilters(false)}}>{item==="todos"?"Todos os veículos":labels[item]}</button>)}</div>}</section>
    <section className="inventory"><div className="section-title"><div><h2>{role==="admin"?"Veículos da frota":"Disponíveis para venda"}</h2><p>{loading?"Atualizando...":`${visible.length} veículo${visible.length!==1?"s":""} encontrado${visible.length!==1?"s":""}`}</p></div></div>
      {loading?<div className="skeleton-grid"><i></i><i></i><i></i><i></i></div>:<div className="vehicle-grid">{visible.map(v=><article className="vehicle-card" key={v.id} onClick={()=>setSelected(v)} tabIndex={0} onKeyDown={e=>e.key==="Enter"&&setSelected(v)}><CarArt vehicle={v}/><div className="vehicle-main"><div className="status-row"><span className={`status ${v.status}`}>{labels[v.status]}</span><span className="year">{v.year}</span></div><h3>{v.brand} {v.model}</h3><div className="facts"><span><small>Quilometragem</small>{v.mileage.toLocaleString("pt-BR")} km</span><span><small>Placa</small>{v.plate}</span></div>{v.damages.length?<p className="damage">⚠ {v.damages.length} avaria{v.damages.length>1?"s":""}</p>:<p className="clean">✓ Sem avarias registradas</p>}</div><button className="details">Ver detalhes <span>→</span></button></article>)}</div>}
      {!loading&&!visible.length&&<div className="empty"><b>{vehicles.length?"Nenhum veículo encontrado":"Estoque ainda vazio"}</b><span>{vehicles.length?"Tente remover os filtros ou alterar sua busca.":role==="admin"?"Cadastre o primeiro veículo para começar.":"Aguarde a publicação dos veículos disponíveis."}</span>{role==="admin"&&!vehicles.length&&<button className="primary" onClick={openCreate}>Cadastrar primeiro veículo</button>}</div>}
    </section>
    {role==="admin"&&<button className="fab" onClick={openCreate}>＋</button>}
    <nav className="bottom-nav"><button className="active">⌂<span>Início</span></button><button>▣<span>Veículos</span></button><button onClick={()=>notify("Relatórios entrarão na próxima versão")}>▥<span>Relatórios</span></button><button>⚙<span>Ajustes</span></button></nav>

    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="detail-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><CarArt vehicle={selected}/><span className={`status ${selected.status}`}>{labels[selected.status]}</span><h2>{selected.brand} {selected.model}</h2><p className="muted">{selected.year} · {selected.mileage.toLocaleString("pt-BR")} km · {selected.plate}</p><hr/><h3>Avarias informadas</h3>{selected.damages.length?<ul>{selected.damages.map(a=><li key={a}>{a}</li>)}</ul>:<p className="clean">✓ Nenhuma avaria registrada</p>}<h3>Observações</h3><p>{selected.notes||"Nenhuma observação adicional."}</p>{role==="admin"?<><div className="status-actions">{selected.status!=="disponivel"&&<button onClick={()=>changeStatus(selected,"disponivel")}>Disponibilizar</button>}{selected.status==="disponivel"&&<button onClick={()=>changeStatus(selected,"reservado")}>Reservar</button>}{selected.status==="reservado"&&<button onClick={()=>changeStatus(selected,"vendido")}>Concluir venda</button>}</div><button className="primary full" onClick={()=>openEdit(selected)}>Editar informações</button></>:<button className="primary full" onClick={()=>notify("Interesse registrado com sucesso")}>Tenho interesse</button>}</article></div>}

    {formOpen&&<div className="modal-backdrop" onClick={()=>setFormOpen(false)}><form className="vehicle-form" onSubmit={save} onClick={e=>e.stopPropagation()}><div className="form-head"><div><p className="eyebrow">ADMINISTRATIVO</p><h2>{editingId?"Editar veículo":"Cadastrar veículo"}</h2></div><button type="button" onClick={()=>setFormOpen(false)}>×</button></div><div className="form-grid"><label>Marca<input required value={draft.brand} onChange={e=>setDraft({...draft,brand:e.target.value})}/></label><label>Modelo e versão<input required value={draft.model} onChange={e=>setDraft({...draft,model:e.target.value})}/></label><label>Ano fabricação/modelo<input required placeholder="2022/2023" value={draft.year} onChange={e=>setDraft({...draft,year:e.target.value})}/></label><label>Quilometragem<input required type="number" min="0" value={draft.mileage} onChange={e=>setDraft({...draft,mileage:Number(e.target.value)})}/></label><label>Placa<input required maxLength={7} value={draft.plate} onChange={e=>setDraft({...draft,plate:e.target.value.toUpperCase()})}/></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Status})}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Foto do veículo<input className="file-input" type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];if(file)try{await upload(file);notify("Foto enviada")}catch(err){setError(err instanceof Error?err.message:"Falha no envio")}}}/><small>{draft.photoUrl?"Foto anexada com sucesso":"JPEG, PNG ou WebP — até 8 MB"}</small></label><label>Avarias <small>uma por linha</small><textarea rows={3} value={draft.damageText} onChange={e=>setDraft({...draft,damageText:e.target.value})}/></label><label>Observações<textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary full" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Cadastrar veículo"}</button></form></div>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </main>
}
